import { router, useFocusEffect } from 'expo-router';

import {
	Alert,
	Animated,
	Linking,
	ScrollView,
	StyleSheet,
	Text,
	TouchableOpacity,
	useColorScheme,
	View
} from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { useThemeStore } from '@/stores/useThemeStore';
import styles from '@/config/styles';
import FooImage from '@/components/icons/hugeicons/FooImage';
import AiScan from '@/components/icons/hugeicons/AiScan';
import Keyboard from '@/components/icons/hugeicons/Keyboard';
import HandSwipeUpward from '@/components/icons/hugeicons/HandSwipeUpward';
import ArrowDoubleUp from '@/components/icons/hugeicons/ArrowDoubleUp';
import { useEffect, useRef, useState } from 'react';
import { useScanStore } from '@/stores/useScanStore';
import QuestionMark from '@/components/icons/hugeicons/QuestionMark';
import { storage } from '@/config/mmkv';
import { useDebouncedCallback } from 'use-debounce';
import { Modal, Portal } from 'react-native-paper';
import { onScroll } from '@/utility/scrollView';
import Disclaimer from '@/components/Disclaimer';
// import { usecamera } from 'react-native-vision-camera';
import Toast from 'react-native-toast-message';
const schema = [
	{
		name: 'Camera Scan',
		description:
			'Point your camera at any product label to instantly identify and analyze ingredients.',
		action_title: 'Open Camera',
		action: (status, requestPermission) => async () => {
			if (!status?.granted) {
				const permission = await requestPermission();

				if (!permission?.granted) {
					Alert.alert(
						'Camera Permission Blocked',
						'You have denied camera permissions. Please enable them in your device settings to use this feature.',
						[
							{ text: 'Cancel', style: 'cancel' },
							{ text: 'Open Settings', onPress: () => Linking.openSettings() }
						]
					);
				}
				return;
			}

			router.push('scanner/scan');
		},
		icon: (size, color) => <AiScan size={size} color={color} />
	},
	{
		name: 'Image Gallery',
		description:
			'Choose a photo from your gallery or library. Perfect for screenshots or saved product photos.',
		action_title: 'Choose Photo',
		action: (setImageBase64, setImageUri) => async () => {
			let result = await ImagePicker.launchImageLibraryAsync({
				mediaTypes: ['images'],
				base64: true,
				selectionLimit: 1,
				allowsEditing: true,
				allowsMultipleSelection: false,
				aspect: [3, 4],
				quality: 1
			});

			if (result.canceled) return;

			setImageBase64(result.assets[0].base64);

			router.replace({
				pathname: 'scanner/processing'
			});
		},
		icon: (size, color) => <FooImage size={size} color={color} />
	},
	{
		name: 'Manual Input',
		description:
			"Don't have a photo? Type the ingredients list manually to get a detailed ingredient analysis.",
		action_title: 'Enter Ingredients',
		action: () => () => {
			router.push('scanner/details');
		},
		icon: (size, color) => <Keyboard size={size} color={color} />
	}
];

const disclaimerSchema = [
	{
		name: 'Analysis Limitations and Safety Disclaimer',
		contents: [
			'By using the BeauWise scanning tool through camera capture, image upload, or manual ingredient entry, and by viewing any analysis results generated by the application, you acknowledge and agree to the following limitations and conditions:'
		]
	},

	{
		name: 'Text-Based Ingredient Analysis Only',
		contents: [
			'BeauWise is an educational ingredient analysis tool that operates solely through text recognition and text matching. The application analyzes ingredient names extracted through Optical Character Recognition (OCR) or entered manually by the user. BeauWise does not perform laboratory testing, chemical analysis, ingredient authentication, product verification, or concentration measurement of any substance contained within a cosmetic product.'
		]
	},

	{
		name: 'Input and Label Accuracy',
		contents: [
			'The accuracy of the analysis depends on the quality and completeness of the information provided. Results may be affected by image quality, lighting conditions, packaging design, OCR recognition errors, incomplete ingredient lists, typographical errors, or incorrect manual entries. BeauWise cannot verify whether the actual contents of a product precisely match the ingredients printed on its packaging or labeling.'
		]
	},
	{
		name: 'Not Medical Advice',
		contents: [
			'The information provided by BeauWise is intended solely for educational and informational purposes. It does not constitute medical advice, diagnosis, treatment, dermatological consultation, or professional healthcare recommendations. Users should not rely on BeauWise as a substitute for professional medical evaluation or treatment.'
		]
	},
	{
		name: 'Regulatory and Safety Information',
		contents: [
			'Any regulatory, safety, or notification-related information displayed within BeauWise is intended for informational purposes only. The presence, absence, or classification of an ingredient should not be interpreted as a guarantee of product safety, effectiveness, suitability, authenticity, or regulatory compliance.'
		]
	},
	{
		name: 'Special Precautions',
		contents: [
			'If you are pregnant, breastfeeding, taking prescription skin medications, undergoing dermatological treatment, or have a diagnosed skin, scalp, or allergic condition, including but not limited to eczema, psoriasis, rosacea, severe acne, or contact dermatitis, consult a licensed dermatologist or qualified healthcare professional before using any new cosmetic product, regardless of the analysis results displayed by BeauWise.'
		]
	},
	{
		name: 'User Responsibility',
		contents: [
			'Users remain solely responsible for evaluating the suitability of any cosmetic product for their individual needs and circumstances. Final purchasing and usage decisions should be made using professional judgment, product labeling, manufacturer guidance, and consultation with qualified healthcare professionals when appropriate.'
		]
	}
];

export default function ScannerScreen() {
	const [status, requestPermission] = ImagePicker.useCameraPermissions();
	const systemTheme = useColorScheme() ?? 'light';
	const themeMode = useThemeStore((state) => state.themeMode);
	const activeTheme = themeMode === 'system' ? systemTheme : themeMode;

	const setImageBase64 = useScanStore((state) => state.setImageBase64);
	const setImageUri = useScanStore((state) => state.setImageUri);

	const [disclaimerButtonActive, setDisclaimerButtonActive] = useState(true);
	const [disclaimerVisible, setDisclaimerVisible] = useState(false);
	const isShownDisclaimer = storage.getBoolean('analysis-disclaimer-shown');

	const showDisclaimer = () => setDisclaimerVisible(true);
	const hideDisclaimer = () => setDisclaimerVisible(false);
	const delayShowDisclaimer = useDebouncedCallback(showDisclaimer, 300);

	const handleDisclaimer = () => {
		hideDisclaimer();

		if (!isShownDisclaimer) {
			storage.set('analysis-disclaimer-shown', true);
		}
	};

	const disclaimerDisable = disclaimerButtonActive && !isShownDisclaimer;

	useEffect(() => {
		if (!isShownDisclaimer) {
			delayShowDisclaimer();
		}
	}, []);

	return (
		<View
			style={{
				flex: 1,
				backgroundColor: styles.theme.colors[activeTheme].screen_background
			}}
		>
			<View
				style={{
					backgroundColor: styles.theme.colors.primary,
					paddingHorizontal: styles.spacing.double_xl,
					paddingTop: 62,
					paddingBottom: styles.spacing.double_xxl,
					flexDirection: 'row',
					alignItems: 'center'
				}}
			>
				<View>
					<Text
						style={{
							fontFamily: styles.font.family,
							fontSize: styles.font.size.xl,
							fontWeight: styles.font.weight.bold,
							color: styles.font.colors._04
						}}
					>
						FDA Product Verifier
					</Text>

					<Text
						style={{
							fontFamily: styles.font.family,
							fontSize: styles.font.size.sm,
							fontWeight: styles.font.weight.light,
							color: styles.font.colors._04
						}}
					>
						Verify FDA Compliance Status
					</Text>
				</View>

				<TouchableOpacity
					onPress={showDisclaimer}
					activeOpacity={0.7}
					style={{ alignSelf: 'center', marginLeft: 'auto' }}
				>
					<QuestionMark
						size={styles.icon.size.xl * 1.4}
						color={styles.background_color._04}
					/>
				</TouchableOpacity>
			</View>

			<Animated.View
				style={{
					...StyleSheet.absoluteFillObject,
					position: 'absolute',
					alignSelf: 'center',
					top: 110,
					rowGap: styles.spacing.one_xxl,
					flex: 1,
					height: '100%'
				}}
			>
				{schema.map(({ name, description, action, icon, action_title }) => {
					return (
						<View
							key={name}
							style={{
								alignSelf: 'center',
								width: '92%',
								padding: styles.spacing.one_xxl,
								borderRadius: styles.border.radius.size.sm,
								backgroundColor: styles.theme.colors[activeTheme].card_background,
								borderColor: styles.theme.colors[activeTheme].card_border,
								borderWidth: 1,
								rowGap: styles.spacing.xl
							}}
						>
							<View
								style={{
									flexDirection: 'row',
									alignItems: 'center',
									columnGap: styles.spacing.lg
								}}
							>
								{icon(styles.icon.size.xl * 1.2, styles.theme.colors.primary)}

								<Text
									style={{
										color: styles.theme.colors[activeTheme].text,
										fontFamily: styles.font.family,
										fontSize: styles.font.size.lg,
										fontWeight: styles.font.weight.semi_bold
									}}
								>
									{name}
								</Text>
							</View>
							<Text
								style={{
									color: styles.theme.colors[activeTheme].text_secondary,
									fontFamily: styles.font.family,
									fontSize: styles.font.size.md,
									fontWeight: styles.font.weight.regular
								}}
							>
								{description}
							</Text>
							<TouchableOpacity
								onPress={
									name === 'Image Gallery'
										? action(setImageBase64, setImageUri)
										: name === 'Camera Scan'
											? action(status, requestPermission)
											: action()
								}
								activeOpacity={0.7}
								style={{
									backgroundColor: styles.theme.colors.primary,
									borderRadius: styles.border.radius.size.sm,
									paddingVertical: styles.spacing.xl
								}}
							>
								<Text
									style={{
										textAlign: 'center',
										color: styles.font.colors._04,
										fontFamily: styles.font.family,
										fontSize: styles.font.size.md,
										fontWeight: styles.font.weight.regular
									}}
								>
									{action_title}
								</Text>
							</TouchableOpacity>
						</View>
					);
				})}
			</Animated.View>

			<Disclaimer
				schema={disclaimerSchema}
				disclaimerVisible={disclaimerVisible}
				disabled={disclaimerDisable}
				onPress={handleDisclaimer}
				backgroundColor={styles.theme.colors.primary}
				setDisclaimerButtonActive={setDisclaimerButtonActive}
			/>
			<View
				style={{
					position: 'absolute',
					alignSelf: 'center',
					justifyContent: 'center',
					top: 710
				}}
			>
				<View
					style={{
						alignItems: 'center',
						justifyContent: 'center',
						rowGap: styles.spacing.md
					}}
				>
					<View>
						<ArrowDoubleUp
							size={styles.icon.size.xl}
							color={styles.theme.colors[activeTheme].icon}
						/>
					</View>
					<Text
						style={{
							fontFamily: styles.font.family,
							color: styles.theme.colors[activeTheme].text,
							fontSize: styles.font.size.md,
							textTransform: 'capitalize',

							textAlign: 'center'
						}}
					>
						Swipe up here to close
					</Text>
				</View>
			</View>
		</View>
	);
}
