export default [
	'Adenosine',
	'Alcohol Denat',
	'Allantoin',
	'Aloe Vera (Aloe barbadensis Miller)',
	'Alpha Arbutin (a-Arbutin)',
	'Alpha Hydroxy Acids (AHA)',
	'Amino Acids (e.g., Taurine, Arginine, Glycine)',
	'Aqua (Water)',
	'Argan Oil (Argania Spinosa Kernel Oil)',
	'Ascorbic Acid (Pure Vitamin C / L-Ascorbic Acid)',
	'Azelaic Acid',
	'Bakuchiol',
	'Beeswax',
	'Behentrimonium Methosulfate (BTMS)',
	'Benzoyl Peroxide',
	'Beta Glucan (β-Glucan)',
	'Beta Hydroxy Acid (BHA)',
	'Biotin (also known as Vitamin B7 or Vitamin H)',
	'Bismuth Oxychloride (and Bismuth compounds)',
	'Butylene Glycol',
	'Caprylic/Capric Triglyceride',
	'Carbomer',
	'Castor Oil',
	'Centella Asiatica',
	'Ceramide',
	'Cetearyl Alcohol',
	'Cetrimonium Chloride',
	'Citric Acid',
	'Clobetasol Propionate',
	'Cocamidopropyl Betaine',
	'Coenzyme Q10 (Ubiquinone)',
	'Collagen (including Hydrolyzed Collagen / Collagen Peptides)',
	'Cyclopentasiloxane',
	'Dimethicone',
	'Disodium EDTA',
	'Ethylhexylglycerin',
	'Ferulic Acid',
	'Fragrance',
	'Ginseng Extract',
	'Gluconolactone',
	'Glycerin',
	'Glycolic Acid',
	'Hyaluronic Acid',
	'Hydrogenated Polyisobutene',
	'Hydroquinone',
	'Iron Oxides',
	'Isododecane',
	'Isopropyl Myristate',
	'Jojoba Oil',
	'Kaolin',
	'Kojic Acid',
	'Lactic Acid',
	'Lanolin',
	'Lead',
	'Lecithin',
	'Madecassoside',
	'Magnesium Ascorbyl Phosphate (MAP)',
	'Mandelic Acid',
	'Mercury',
	'Mica',
	'Mineral Oil',
	'Niacinamide',
	'Nylon-12',
	'Octinoxate',
	'Octocrylene',
	'Oleic Acid',
	'Oxybenzone',
	'Panthenol / Dexpanthenol (Vitamin B5)',
	'Parabens (including Methylparaben, Propylparaben, Butylparaben, and Ethylparaben)',
	'PEG (Polyethylene Glycol)',
	'Peptides (Cosmetic / Bioactive Peptides)',
	'Phenoxyethanol (or 2-phenoxyethanol)',
	'Phthalates',
	'Polysorbates',
	'Propylene Glycol',
	'Resveratrol',
	'Retinal (Retinaldehyde)',
	'Retinol (Vitamin A)',
	'Retinyl Palmitate',
	'Salicylic Acid',
	'Shea Butter',
	'Silica (Amorphous Silica / Silicon Dioxide)',
	'Snail Mucin (Snail Secretion Filtrate)',
	'Sodium Hyaluronate (SH)',
	'Sodium Laureth Sulfate (SLES)',
	'Sodium Lauryl Sulfate (SLS)',
	'Sodium PCA',
	'Squalane',
	'Stearic Acid',
	'Sulfur',
	'Talc',
	'Tea Tree Oil (Melaleuca alternifolia)',
	'Titanium Dioxide (TiO2)',
	'Tocopherol (Vitamin E)',
	'Tretinoin',
	'Triclosan (TCS)',
	'Urea',
	'Vitamin C Derivatives (e.g., Magnesium Ascorbyl Phosphate, Ascorbyl Glucoside, Sodium Ascorbyl Phosphate)',
	'Witch Hazel (Hamamelis virginiana)',
	'Xanthan Gum',
	'Yeast Extract (Saccharomyces Ferment)',
	'Zinc Oxide (ZnO)',
	'Zinc PCA'
];
