export default [
	'Adenosine',
	'Alcohol Denat.',
	'Allantoin',
	'Aloe Vera (Aloe barbadensis Miller)',
	'Alpha Arbutin (a-Arbutin)',
	'Alpha Hydroxy Acids (AHA)',
	'Amino Acids (e.g., Taurine, Arginine, Glycine)',
	'Aqua (Water, Distilled Water)',
	'Argan Oil (Argania Spinosa Kernel Oil)',
	'Ascorbic Acid (Pure Vitamin C / L-Ascorbic Acid)',
	'Azelaic Acid',
	'Bakuchiol',
	'Beeswax (also known in cosmetics as Yellow wax / Cera flava or White wax / Cera alba)',
	'Behentrimonium Methosulfate (BTMS)',
	'Benzoyl Peroxide',
	'Beta Glucan (β-Glucan)',
	'Beta Hydroxy Acid (BHA)',
	'Biotin (also known as Vitamin B7 or Vitamin H)',
	'Bismuth Oxychloride (and Bismuth compounds)',
	'Butylene Glycol',
	'Caprylic/Capric Triglyceride (also sometimes referred to as fractionated coconut oil or medium-chain triglycerides)',
	'Carbomer',
	'Castor Oil',
	'Centella Asiatica (also known as Gotu Kola or Tiger Grass)',
	'Ceramide',
	'Cetearyl Alcohol (also known as cetostearyl alcohol)',
	'Cetrimonium Chloride (also known as Alkyl trimethyl ammonium chloride)',
	'Citric Acid',
	'Clobetasol Propionate',
	'Cocamidopropyl Betaine',
	'Coenzyme Q10 (Ubiquinone)',
	'Collagen (including Hydrolyzed Collagen / Collagen Peptides)',
	'Cyclopentasiloxane (also known as decamethylcyclopentasiloxane or D5)',
	'Dimethicone',
	'Disodium EDTA',
	'Ethylhexylglycerin (also known as octoxyglycerin or Sensiva SC50)',
	'Ferulic Acid',
	'Fragrance (Parfum)',
	'Ginseng Extract',
	'Gluconolactone',
	'Glycerin (also known as Glycerol or Glycerine)',
	'Glycolic Acid',
	'Hyaluronic Acid (also known as Hyaluronan or Hyaluronate)',
	'Hydrogenated Polyisobutene',
	'Hydroquinone',
	'Iron Oxides (Iron Oxide Nanoparticles / FeO-NP)',
	'Isododecane',
	'Isopropyl Myristate',
	'Jojoba Oil',
	'Kaolin (Clay)',
	'Kojic Acid',
	'Lactic Acid',
	'Lanolin',
	'Lead',
	'Lecithin',
	'Madecassoside (also known as Asiaticoside A)',
	'Magnesium Ascorbyl Phosphate (MAP)',
	'Mandelic Acid',
	'Mercury (may be listed as Hg, mercuric iodide, mercury oxide, mercurous chloride, ethyl mercury, phenyl mercuric salts, ammoniated mercury, amide chloride of mercury, or "poison")',
	'Mica',
	'Mineral Oil',
	'Niacinamide (Vitamin B3 / Nicotinamide)',
	'Nylon-12',
	'Octinoxate (Ethylhexyl Methoxycinnamate / EHMC)',
	'Octocrylene',
	'Oleic Acid',
	'Oxybenzone (Benzophenone-3)',
	'Panthenol / Dexpanthenol (Vitamin B5)',
	'Parabens (including Methylparaben, Propylparaben, Butylparaben, and Ethylparaben)',
	'PEG (Polyethylene Glycol)',
	'Peptides (Cosmetic / Bioactive Peptides)',
	'Phenoxyethanol (or 2-phenoxyethanol)',
	'Phthalates (including Dibutylphthalate/DBP, Dimethylphthalate/DMP, and Diethylphthalate/DEP)',
	'Polysorbates (e.g., Polysorbate 20, 40, 60, 80)',
	'Propylene Glycol (and Propylene Glycol Esters)',
	'Resveratrol',
	'Retinal (Retinaldehyde)',
	'Retinol (Vitamin A, retinoic acid)',
	'Retinyl Palmitate',
	'Salicylic Acid',
	'Shea Butter',
	'Silica (Amorphous Silica / Silicon Dioxide)',
	'Snail Mucin (Snail Secretion Filtrate)',
	'Sodium Hyaluronate (SH)',
	'Sodium Laureth Sulfate (SLES)',
	'Sodium Lauryl Sulfate (SLS)',
	'Sodium PCA',
	'Squalane',
	'Stearic Acid',
	'Sulfur',
	'Talc',
	'Tea Tree Oil (Melaleuca alternifolia)',
	'Titanium Dioxide (TiO2)',
	'Tocopherol (Vitamin E)',
	'Tretinoin',
	'Triclosan (TCS)',
	'Urea',
	'Vitamin C Derivatives (e.g., Magnesium Ascorbyl Phosphate, Ascorbyl Glucoside, Sodium Ascorbyl Phosphate)',
	'Witch Hazel (Hamamelis virginiana)',
	'Xanthan Gum',
	'Yeast Extract (Saccharomyces Ferment)',
	'Zinc Oxide (ZnO)',
	'Zinc PCA'
];
